name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Change this to your default branch name if it's different

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node.js âš™ï¸
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: urban-detective/package-lock.json

      - name: Install Dependencies ğŸ“¦
        run: npm ci
        working-directory: urban-detective

      - name: Build ğŸ—ï¸
        run: npx ng build --configuration production --base-href /urban-detective/
        working-directory: urban-detective

      - name: Create 404 Page ğŸ“„
        run: cp dist/urban-detective/browser/index.html dist/urban-detective/browser/404.html
        working-directory: urban-detective

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: urban-detective/dist/urban-detective/browser # Ensure this matches your Angular build output path
          branch: gh-pages
